#!/bin/bash
hyprctl dispatch fullscreen

SESSION_NAME="$1"

# Check if session already exists
if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  echo "Session '$SESSION_NAME' already exists. Attaching..."
  tmux attach-session -t "$SESSION_NAME"
else
  # Create new detached session
  tmux new-session -d -s "$SESSION_NAME"

  tmux rename-window -t "$SESSION_NAME:1" "nvim"
  tmux send-keys -t "$SESSION_NAME:1" "nvim" C-m " qS"

  tmux new-window -t "$SESSION_NAME" -n "extra"

  tmux attach-session -t "$SESSION_NAME:1"
fi

